// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVCZzn-qMEVo8i6qVDoHsCR_ZvdE6SNGk',
    appId: '1:715360945619:web:f25745fa202ac9758fdb26',
    messagingSenderId: '715360945619',
    projectId: 'logiclegends-81f71',
    authDomain: 'logiclegends-81f71.firebaseapp.com',
    storageBucket: 'logiclegends-81f71.appspot.com',
    measurementId: 'G-L7SD14QP4L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJFiQox7dVKDNgNgpT_VkUMtzeaaeUMWQ',
    appId: '1:715360945619:android:b6e9dc9cd1e66e6d8fdb26',
    messagingSenderId: '715360945619',
    projectId: 'logiclegends-81f71',
    storageBucket: 'logiclegends-81f71.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrD7HjC4nzk6m6d6AY-i8-aEgmCs9mvgA',
    appId: '1:715360945619:ios:86024142887e9f2f8fdb26',
    messagingSenderId: '715360945619',
    projectId: 'logiclegends-81f71',
    storageBucket: 'logiclegends-81f71.appspot.com',
    iosClientId: '715360945619-f8ngpvtq8kotsaen83hsjml956rqne0h.apps.googleusercontent.com',
    iosBundleId: 'com.example.logintest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrD7HjC4nzk6m6d6AY-i8-aEgmCs9mvgA',
    appId: '1:715360945619:ios:cbd0e3d45ee833ba8fdb26',
    messagingSenderId: '715360945619',
    projectId: 'logiclegends-81f71',
    storageBucket: 'logiclegends-81f71.appspot.com',
    iosClientId: '715360945619-t58i0cutjsk8kdv6t5urqehc4lbfd6g0.apps.googleusercontent.com',
    iosBundleId: 'com.example.logintest.RunnerTests',
  );
}
